version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
#      - POSTGRES_PASSWORD='12345'
      - POSTGRES_DB="course_drf"
      - PGDATA=/var/lib/postgresql/data/pgdata
#      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


  app:
    build: .
#    command: python manage.py migrate --database course_drf && python manage.py runserver 0.0.0.0:8000
    tty: true
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: /bin/bash -c "celery -A conf worker -l INFO"
    depends_on:
      - app
      - redis

  celery_beat:
    build: .
    restart: always
    tty: true
    command: /bin/bash -c "celery -A conf beat -l INFO -S django"
    depends_on:
      - app
      - redis


volumes:
  pg_data:




