# Generated by Django 3.2.12 on 2023-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_payment_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1500, null=True, verbose_name='цена'),
        ),
    ]
