# Generated by Django 3.2.12 on 2023-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_payment_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, default='unpaid', help_text='статус оплаты', max_length=150, null=True, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, help_text='url для оплаты', null=True, verbose_name='url для оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID сессии Stripe', max_length=150, null=True, verbose_name='ID сессии Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.TextField(blank=True, help_text='сессия для оплаты', null=True, verbose_name='сессия для оплаты'),
        ),
    ]
