# Generated by Django 3.2.12 on 2023-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20230917_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего обновления'),
        ),
    ]
