# Generated by Django 3.2.12 on 2023-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.TextField(blank=True, help_text='url для оплаты', null=True, verbose_name='url для оплаты'),
        ),
    ]
